# config context path to "/" by setting an empty string
server:
  contextPath:

app:
  name: spring-security-jwt

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  claim:
     userAuthorities: aut
     userId: uid
  route:
    authentication:
      path: auth

spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource
  datasource:
    platform: h2
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

