-- noinspection SqlNoDataSourceInspectionForFile

-- noinspection SqlDialectInspectionForFile

INSERT INTO USERS (ID, EMAIL, ENABLED, PASSWORD, USERNAME) VALUES (1000, 'user@gmail.com', true, '$2a$10$7nJL8L0VaW8fZj4hMRocwuuBamuCCYEUvRIpwWy.j2lqkIllqBKA.', 'user');
INSERT INTO USERS (ID, EMAIL, ENABLED, PASSWORD, USERNAME) VALUES (2000, 'admin@gmail.com', true, '$2a$10$ATCkFXIZFTPsNjpopNajeOaxKl683zZN0lwT0gkvVuTS7JZd08JZu', 'admin');

INSERT INTO AUTHORITIES (ID, ROLE, USER_ID) VALUES (1001, 'ROLE_USER', 1000);
INSERT INTO AUTHORITIES (ID, ROLE, USER_ID) VALUES (2001, 'ROLE_USER', 2000);
INSERT INTO AUTHORITIES (ID, ROLE, USER_ID) VALUES (2002, 'ROLE_ADMIN', 2000);
